/**
 * Official Employee Directory from Master Excel
 * Used for Lucky Draw Registration and Award Ceremony
 */
window.TLQM_EMPLOYEES = [
  {
    "stt": 1,
    "code": "005",
    "name": "Vũ Việt Tùng",
    "dept": "Ban Tổng Giám đốc",
    "subdept": "Quản lý chung",
    "pos": "Phó Tổng Giám đốc",
    "gender": "Nam",
    "company": "Phú Anh",
    "isGala": true
  },
  {
    "stt": 2,
    "code": "087",
    "name": "Đinh Thị Bờ",
    "dept": "Hành chính - Nhân sự",
    "subdept": "Hành chính",
    "pos": "Nhân viên bếp",
    "gender": "Nữ",
    "company": "Sơn Cảng",
    "isGala": true
  },
  {
    "stt": 3,
    "code": "069",
    "name": "Đinh Văn Thảo",
    "dept": "Hành chính - Nhân sự",
    "subdept": "Hành chính",
    "pos": "Nhân viên Lái xe",
    "gender": "Nam",
    "company": "Sơn Cảng",
    "isGala": true
  },
  {
    "stt": 4,
    "code": "037",
    "name": "Phạm Thị Hằng",
    "dept": "Hành chính - Nhân sự",
    "subdept": "Hành chính",
    "pos": "Nhân viên tạp vụ",
    "gender": "Nữ",
    "company": "Phú Anh",
    "isGala": true
  },
  {
    "stt": 5,
    "code": "068",
    "name": "Hà Thị Hòa",
    "dept": "Hành chính - Nhân sự",
    "subdept": "Hành chính",
    "pos": "Nhân viên tạp vụ",
    "gender": "Nữ",
    "company": "Sơn Cảng",
    "isGala": true
  },
  {
    "stt": 6,
    "code": "016",
    "name": "Bế Ngọc Dung",
    "dept": "Hành chính - Nhân sự",
    "subdept": "Hành chính - Nhân sự",
    "pos": "Nhân viên Hành chính - Nhân sự",
    "gender": "Nữ",
    "company": "Phú Anh",
    "isGala": true
  },
  {
    "stt": 7,
    "code": "138",
    "name": "Hà Huy Hùng",
    "dept": "Kế hoạch - Dự án",
    "subdept": "Ban Quản lý dự án",
    "pos": "Kỹ sư cơ điện",
    "gender": "Nam",
    "company": "Sơn Cảng",
    "isGala": false
  },
  {
    "stt": 8,
    "code": "066",
    "name": "Nguyễn Quang Đạt",
    "dept": "Kế hoạch - Dự án",
    "subdept": "Ban Quản lý dự án",
    "pos": "Trưởng ban Quản lý dự án",
    "gender": "Nam",
    "company": "Tà Lùng Quang Minh",
    "isGala": true
  },
  {
    "stt": 9,
    "code": "027",
    "name": "Lương Văn Hiện",
    "dept": "Kế hoạch - Dự án",
    "subdept": "Ban Quản lý dự án",
    "pos": "Trưởng phòng Kế hoạch - Dự án",
    "gender": "Nam",
    "company": "Phú Anh",
    "isGala": false
  },
  {
    "stt": 10,
    "code": "055",
    "name": "Hà Đoàn Diệu",
    "dept": "Kế hoạch - Dự án",
    "subdept": "Kế hoạch và Pháp lý",
    "pos": "Chuyên viên Kế hoạch - Dự án",
    "gender": "Nữ",
    "company": "Sơn Cảng",
    "isGala": true
  },
  {
    "stt": 11,
    "code": "013",
    "name": "Phạm Thị Khánh Vân",
    "dept": "Kế hoạch - Dự án",
    "subdept": "Kế hoạch và Pháp lý",
    "pos": "Phó phòng Kế hoạch - Dự án",
    "gender": "Nữ",
    "company": "Phú Anh",
    "isGala": true
  },
  {
    "stt": 12,
    "code": "038",
    "name": "Hoàng Xuân Phúc",
    "dept": "Kinh doanh",
    "subdept": "Phát triển thị trường",
    "pos": "Chuyên viên Kinh doanh",
    "gender": "Nam",
    "company": "Phú Anh",
    "isGala": true
  },
  {
    "stt": 13,
    "code": "061",
    "name": "Lý Thị Thanh Hiếu",
    "dept": "Kinh doanh",
    "subdept": "Phát triển thị trường",
    "pos": "Chuyên viên Kinh doanh",
    "gender": "Nữ",
    "company": "Sơn Cảng",
    "isGala": true
  },
  {
    "stt": 14,
    "code": "039",
    "name": "Mông Thị Hằng",
    "dept": "Kinh doanh",
    "subdept": "Phát triển thị trường",
    "pos": "Nhân viên Kinh doanh",
    "gender": "Nữ",
    "company": "Phú Anh",
    "isGala": true
  },
  {
    "stt": 15,
    "code": "056",
    "name": "Vũ Văn Hoán",
    "dept": "Kinh doanh",
    "subdept": "Phát triển thị trường",
    "pos": "Phó phòng Kinh doanh",
    "gender": "Nam",
    "company": "Sơn Cảng",
    "isGala": true
  },
  {
    "stt": 16,
    "code": "047",
    "name": "Nguyễn Thị Thu Hiền",
    "dept": "Kinh doanh",
    "subdept": "Xuất nhập khẩu",
    "pos": "Nhân viên Thủ tục Xuất nhập khẩu",
    "gender": "Nữ",
    "company": "Phú Anh",
    "isGala": false
  },
  {
    "stt": 17,
    "code": "109",
    "name": "Đặng Thị Minh Huyền",
    "dept": "Kinh doanh",
    "subdept": "Xuất nhập khẩu",
    "pos": "Nhân viên Thủ tục Xuất nhập khẩu",
    "gender": "Nữ",
    "company": "Song Toàn",
    "isGala": false
  },
  {
    "stt": 18,
    "code": "062",
    "name": "Hoàng Bằng Giang",
    "dept": "Kinh doanh",
    "subdept": "Xuất nhập khẩu",
    "pos": "Nhân viên Xuất nhập khẩu",
    "gender": "Nữ",
    "company": "Sơn Cảng",
    "isGala": true
  },
  {
    "stt": 19,
    "code": "022",
    "name": "Hoàng Nhật Ánh",
    "dept": "Tài chính - Kế toán",
    "subdept": "Kế toán",
    "pos": "Nhân viên Kế toán",
    "gender": "Nữ",
    "company": "Phú Anh",
    "isGala": false
  },
  {
    "stt": 20,
    "code": "075",
    "name": "Nguyễn Ngọc Ánh",
    "dept": "Tài chính - Kế toán",
    "subdept": "Kế toán",
    "pos": "Nhân viên Kế toán",
    "gender": "Nữ",
    "company": "Sơn Cảng",
    "isGala": false
  },
  {
    "stt": 21,
    "code": "106",
    "name": "Trần Quốc Toản",
    "dept": "Vận hành",
    "subdept": "An ninh",
    "pos": "Nhân viên An ninh",
    "gender": "Nam",
    "company": "Sơn Cảng",
    "isGala": true
  },
  {
    "stt": 22,
    "code": "031",
    "name": "Lương Duy Thái",
    "dept": "Vận hành",
    "subdept": "An ninh",
    "pos": "Trưởng ca An ninh",
    "gender": "Nam",
    "company": "Phú Anh",
    "isGala": true
  },
  {
    "stt": 23,
    "code": "076",
    "name": "Nguyễn Hoài Nam",
    "dept": "Vận hành",
    "subdept": "Điều phối",
    "pos": "Công nhân bốc xếp",
    "gender": "Nam",
    "company": "Sơn Cảng",
    "isGala": true
  },
  {
    "stt": 24,
    "code": "081",
    "name": "Tăng Văn Tuấn",
    "dept": "Vận hành",
    "subdept": "Điều phối",
    "pos": "Công nhân bốc xếp",
    "gender": "Nam",
    "company": "Sơn Cảng",
    "isGala": true
  },
  {
    "stt": 25,
    "code": "092",
    "name": "Hoàng Hoài Phong",
    "dept": "Vận hành",
    "subdept": "Điều phối",
    "pos": "Công nhân bốc xếp",
    "gender": "Nam",
    "company": "Sơn Cảng",
    "isGala": false
  },
  {
    "stt": 26,
    "code": "094",
    "name": "Luân Văn Mạnh",
    "dept": "Vận hành",
    "subdept": "Điều phối",
    "pos": "Công nhân bốc xếp",
    "gender": "Nam",
    "company": "Sơn Cảng",
    "isGala": true
  },
  {
    "stt": 27,
    "code": "095",
    "name": "Nguyễn Văn Bắc",
    "dept": "Vận hành",
    "subdept": "Điều phối",
    "pos": "Công nhân bốc xếp",
    "gender": "Nam",
    "company": "Sơn Cảng",
    "isGala": false
  },
  {
    "stt": 28,
    "code": "126",
    "name": "Lục Văn Quảng",
    "dept": "Vận hành",
    "subdept": "Điều phối",
    "pos": "Công nhân bốc xếp",
    "gender": "Nam",
    "company": "Sơn Cảng",
    "isGala": true
  },
  {
    "stt": 29,
    "code": "133",
    "name": "Đàm Thị Hân",
    "dept": "Vận hành",
    "subdept": "Điều phối",
    "pos": "Công nhân bốc xếp",
    "gender": "Nữ",
    "company": "Sơn Cảng",
    "isGala": true
  },
  {
    "stt": 30,
    "code": "134",
    "name": "Đàm Thị Vụ",
    "dept": "Vận hành",
    "subdept": "Điều phối",
    "pos": "Công nhân bốc xếp",
    "gender": "Nữ",
    "company": "Sơn Cảng",
    "isGala": true
  },
  {
    "stt": 31,
    "code": "135",
    "name": "Đàm Thị Liệng",
    "dept": "Vận hành",
    "subdept": "Điều phối",
    "pos": "Công nhân bốc xếp",
    "gender": "Nữ",
    "company": "Sơn Cảng",
    "isGala": true
  },
  {
    "stt": 32,
    "code": "139",
    "name": "Chu Thị Hồng",
    "dept": "Vận hành",
    "subdept": "Điều phối",
    "pos": "Công nhân bốc xếp",
    "gender": "Nữ",
    "company": "Sơn Cảng",
    "isGala": true
  },
  {
    "stt": 33,
    "code": "034",
    "name": "Hoàng Văn Võ",
    "dept": "Vận hành",
    "subdept": "Điều phối",
    "pos": "Nhân viên Điều phối",
    "gender": "Nam",
    "company": "Phú Anh",
    "isGala": true
  },
  {
    "stt": 34,
    "code": "054",
    "name": "Nguyễn Cao Cường",
    "dept": "Vận hành",
    "subdept": "Điều phối",
    "pos": "Nhân viên Điều phối",
    "gender": "Nam",
    "company": "Phú Anh",
    "isGala": true
  },
  {
    "stt": 35,
    "code": "030",
    "name": "Lương Văn Thành",
    "dept": "Vận hành",
    "subdept": "Điều phối",
    "pos": "Nhân viên nghiệp vụ cổng cảng và kho bãi",
    "gender": "Nam",
    "company": "Phú Anh",
    "isGala": true
  },
  {
    "stt": 36,
    "code": "006",
    "name": "Trịnh Công Nguyên",
    "dept": "Vận hành",
    "subdept": "Điều phối",
    "pos": "Trưởng bộ phận nghiệp vụ cổng cảng và kho bãi",
    "gender": "Nam",
    "company": "Phú Anh",
    "isGala": true
  },
  {
    "stt": 37,
    "code": "046",
    "name": "Hoàng Minh Hải",
    "dept": "Vận hành",
    "subdept": "Điều phối",
    "pos": "Trưởng ca Điều phối",
    "gender": "Nam",
    "company": "Phú Anh",
    "isGala": false
  },
  {
    "stt": 38,
    "code": "130",
    "name": "Nông Quốc Việt",
    "dept": "Vận hành",
    "subdept": "Hành chính",
    "pos": "Nhân viên Công nghệ thông tin",
    "gender": "Nam",
    "company": "Sơn Cảng",
    "isGala": true
  },
  {
    "stt": 39,
    "code": "007",
    "name": "Nguyễn Xuân Thành",
    "dept": "Vận hành",
    "subdept": "Hành chính",
    "pos": "Trưởng bộ phận Công nghệ thông tin",
    "gender": "Nam",
    "company": "Phú Anh",
    "isGala": true
  },
  {
    "stt": 40,
    "code": "070",
    "name": "Nguyễn Thành Trung",
    "dept": "Vận hành",
    "subdept": "Quản lý chung",
    "pos": "Quyền Phó phòng Vận hành",
    "gender": "Nam",
    "company": "Tà Lùng Quang Minh",
    "isGala": true
  },
  {
    "stt": 41,
    "code": "050",
    "name": "Trần Trung Kiên",
    "dept": "Vận hành",
    "subdept": "Quản lý chung",
    "pos": "Trưởng phòng Vận hành",
    "gender": "Nam",
    "company": "Phú Anh",
    "isGala": true
  },
  {
    "stt": 42,
    "code": "051",
    "name": "Hoàng Văn Kiên",
    "dept": "Vận hành",
    "subdept": "Vận hành thiết bị",
    "pos": "Nhân viên vận hành thiết bị",
    "gender": "Nam",
    "company": "Phú Anh",
    "isGala": true
  },
  {
    "stt": 43,
    "code": "129",
    "name": "Nông Hồng Hưng",
    "dept": "Vận hành",
    "subdept": "Vận hành thiết bị",
    "pos": "Nhân viên vận hành thiết bị",
    "gender": "Nam",
    "company": "Sơn Cảng",
    "isGala": true
  },
  {
    "stt": 44,
    "code": "131",
    "name": "Lâm Hữu Huy",
    "dept": "Vận hành",
    "subdept": "Vận hành thiết bị",
    "pos": "Nhân viên vận hành thiết bị",
    "gender": "Nam",
    "company": "Sơn Cảng",
    "isGala": true
  },
  {
    "stt": 45,
    "code": "003",
    "name": "Trần Văn Lợi",
    "dept": "Vận tải",
    "subdept": "Quản lý chung",
    "pos": "Trưởng phòng Vận tải",
    "gender": "Nam",
    "company": "Phú Anh",
    "isGala": true
  },
  {
    "stt": 46,
    "code": "103",
    "name": "Đàm Văn Cương",
    "dept": "Vận tải",
    "subdept": "Vận tải",
    "pos": "Chuyên viên điều phối vận tải",
    "gender": "Nam",
    "company": "Sơn Cảng",
    "isGala": true
  },
  {
    "stt": 47,
    "code": "004",
    "name": "Nguyễn Hồng Nhung",
    "dept": "Ban Tổng Giám đốc",
    "subdept": "Hành chính",
    "pos": "Trợ lý Ban Tổng Giám đốc",
    "gender": "Nữ",
    "company": "Phú Anh",
    "isGala": true
  },
  {
    "stt": 48,
    "code": "002",
    "name": "Trần Thị Thủy",
    "dept": "Ban Tổng Giám đốc",
    "subdept": "Quản lý chung",
    "pos": "Phó Tổng Giám đốc",
    "gender": "Nữ",
    "company": "Phú Anh",
    "isGala": true
  },
  {
    "stt": 49,
    "code": "001",
    "name": "Lương Khắc Định",
    "dept": "Ban Tổng Giám đốc",
    "subdept": "Quản lý chung",
    "pos": "Tổng Giám đốc",
    "gender": "Nam",
    "company": "Phú Anh",
    "isGala": true
  },
  {
    "stt": 50,
    "code": "028",
    "name": "Ngô Thị Nga",
    "dept": "Hành chính - Nhân sự",
    "subdept": "Hành chính",
    "pos": "Nhân viên bếp",
    "gender": "Nữ",
    "company": "Phú Anh",
    "isGala": true
  },
  {
    "stt": 51,
    "code": "067",
    "name": "Vũ Mạnh Tuấn",
    "dept": "Hành chính - Nhân sự",
    "subdept": "Hành chính",
    "pos": "Nhân viên Lái xe",
    "gender": "Nam",
    "company": "Tà Lùng Quang Minh",
    "isGala": true
  },
  {
    "stt": 52,
    "code": "035",
    "name": "Phạm Hồng Quyên",
    "dept": "Hành chính - Nhân sự",
    "subdept": "Hành chính - Nhân sự",
    "pos": "Chuyên viên Hành chính - Nhân sự",
    "gender": "Nữ",
    "company": "Phú Anh",
    "isGala": true
  },
  {
    "stt": 53,
    "code": "120",
    "name": "Hoàng Hiếu Ngân",
    "dept": "Hành chính - Nhân sự",
    "subdept": "Nhân sự",
    "pos": "Chuyên viên C&B",
    "gender": "Nữ",
    "company": "Sơn Cảng",
    "isGala": true
  },
  {
    "stt": 54,
    "code": "096",
    "name": "Ngô Ngọc Trà",
    "dept": "Hành chính - Nhân sự",
    "subdept": "Pháp chế",
    "pos": "Chuyên viên pháp chế",
    "gender": "Nữ",
    "company": "Tà Lùng Quang Minh",
    "isGala": true
  },
  {
    "stt": 55,
    "code": "015",
    "name": "Nguyễn Huyền Trang",
    "dept": "Hành chính - Nhân sự",
    "subdept": "Quản lý chung",
    "pos": "Trưởng phòng Hành chính - Nhân sự",
    "gender": "Nữ",
    "company": "Phú Anh",
    "isGala": true
  },
  {
    "stt": 56,
    "code": "104",
    "name": "Trần Thị Minh Tâm",
    "dept": "Kinh doanh",
    "subdept": "Dịch vụ khách hàng",
    "pos": "Chuyên viên Dịch vụ khách hàng",
    "gender": "Nữ",
    "company": "Sơn Cảng",
    "isGala": true
  },
  {
    "stt": 57,
    "code": "111",
    "name": "Phùng Ngọc Ánh",
    "dept": "Kinh doanh",
    "subdept": "Marketing",
    "pos": "Chuyên viên Marketing",
    "gender": "Nữ",
    "company": "Sơn Cảng",
    "isGala": true
  },
  {
    "stt": 58,
    "code": "119",
    "name": "Hoàng Minh Quyền",
    "dept": "Kinh doanh",
    "subdept": "Marketing",
    "pos": "Chuyên viên Thiết kế",
    "gender": "Nam",
    "company": "Sơn Cảng",
    "isGala": true
  },
  {
    "stt": 59,
    "code": "009",
    "name": "Triệu Quang Khoa",
    "dept": "Kinh doanh",
    "subdept": "Marketing",
    "pos": "Phó phòng Kinh doanh",
    "gender": "Nam",
    "company": "Phú Anh",
    "isGala": true
  },
  {
    "stt": 60,
    "code": "112",
    "name": "Nguyễn Thị Hằng",
    "dept": "Tài chính - Kế toán",
    "subdept": "Kế toán",
    "pos": "Nhân viên Kế toán doanh thu",
    "gender": "Nữ",
    "company": "May Kind",
    "isGala": true
  },
  {
    "stt": 61,
    "code": "008",
    "name": "Trần Thị Thuận",
    "dept": "Tài chính - Kế toán",
    "subdept": "Kế toán",
    "pos": "Nhân viên Kế toán Thanh toán",
    "gender": "Nữ",
    "company": "Phú Anh",
    "isGala": true
  },
  {
    "stt": 62,
    "code": "121",
    "name": "Nguyễn Thị Ngọc Ánh",
    "dept": "Tài chính - Kế toán",
    "subdept": "Kế toán",
    "pos": "Nhân viên Kế toán thuế",
    "gender": "Nữ",
    "company": "Sơn Cảng",
    "isGala": true
  },
  {
    "stt": 63,
    "code": "010",
    "name": "Nguyễn Thị Hương",
    "dept": "Tài chính - Kế toán",
    "subdept": "Quản lý chung",
    "pos": "Trưởng phòng Tài chính - Kế toán",
    "gender": "Nữ",
    "company": "Phú Anh",
    "isGala": true
  },
  {
    "stt": 64,
    "code": "011",
    "name": "Tống Thị Hoàn",
    "dept": "Thẩm định - Mua sắm",
    "subdept": "Mua hàng Vận hành",
    "pos": "Trưởng bộ phận Thẩm định - Mua sắm vận hành",
    "gender": "Nữ",
    "company": "Phú Anh",
    "isGala": true
  },
  {
    "stt": 65,
    "code": "059",
    "name": "Lê Trần Đức",
    "dept": "Thẩm định - Mua sắm",
    "subdept": "Thẩm định Dự án",
    "pos": "Phó phòng Thẩm định Dự án",
    "gender": "Nam",
    "company": "Phú Anh",
    "isGala": true
  },
  {
    "stt": 66,
    "code": "117",
    "name": "Trần Ánh Ngọc",
    "dept": "Thẩm định - Mua sắm",
    "subdept": "Vận hành",
    "pos": "Chuyên viên Thẩm định - Mua sắm",
    "gender": "Nữ",
    "company": "Sơn Cảng",
    "isGala": true
  },
  {
    "stt": 67,
    "code": "",
    "name": "Ngô Thị Thảo Vân",
    "dept": "GreenTech",
    "subdept": "",
    "pos": "Khách",
    "gender": "Nữ",
    "company": "Tà Lùng Quang Minh",
    "isGala": true
  },
  {
    "stt": 68,
    "code": "",
    "name": "Trần Quốc Huy",
    "dept": "GreenTech",
    "subdept": "",
    "pos": "Khách",
    "gender": "Nam",
    "company": "Tà Lùng Quang Minh",
    "isGala": true
  },
  {
    "stt": 69,
    "code": "",
    "name": "Nguyễn Thị Quỳnh Như",
    "dept": "Nông Sản Việt",
    "subdept": "",
    "pos": "Khách",
    "gender": "Nữ",
    "company": "Tà Lùng Quang Minh",
    "isGala": true
  },
  {
    "stt": 70,
    "code": "",
    "name": "Võ Thị Thu Huyền",
    "dept": "GreenTech",
    "subdept": "",
    "pos": "Khách",
    "gender": "Nữ",
    "company": "Tà Lùng Quang Minh",
    "isGala": false
  },
  {
    "stt": 71,
    "code": "",
    "name": "Nguyễn Hoàng Lê",
    "dept": "GreenTech",
    "subdept": "",
    "pos": "Khách",
    "gender": "Nam",
    "company": "Tà Lùng Quang Minh",
    "isGala": false
  },
  {
    "stt": 72,
    "code": "",
    "name": "Chị Mai",
    "dept": "CTV",
    "subdept": "",
    "pos": "Khách",
    "gender": "Nữ",
    "company": "Tà Lùng Quang Minh",
    "isGala": false
  },
  {
    "stt": 73,
    "code": "",
    "name": "Chị Huệ",
    "dept": "CTV",
    "subdept": "",
    "pos": "Khách",
    "gender": "Nữ",
    "company": "Tà Lùng Quang Minh",
    "isGala": false
  },
  {
    "stt": 74,
    "code": "",
    "name": "Phạm Tiến Dũng",
    "dept": "Dũng Phát",
    "subdept": "",
    "pos": "Khách",
    "gender": "Nam",
    "company": "Tà Lùng Quang Minh",
    "isGala": true
  },
  {
    "stt": 75,
    "code": "",
    "name": "Ngô Văn Hoàn",
    "dept": "GreenTech",
    "subdept": "",
    "pos": "Khách",
    "gender": "Nam",
    "company": "Tà Lùng Quang Minh",
    "isGala": true
  },
  {
    "stt": 70,
    "code": "",
    "name": "Mr. Nguyễn Văn Thắng",
    "dept": "HĐQT",
    "subdept": "",
    "pos": "Khách",
    "gender": "Nam",
    "company": "Phú Anh",
    "isGala": false
  },
  {
    "stt": 77,
    "code": "",
    "name": "Ms. Bùi Thị Huyền Trang",
    "dept": "Phu nhân HĐQT",
    "subdept": "",
    "pos": "Khách",
    "gender": "",
    "company": "Tà Lùng Quang Minh",
    "isGala": false
  },
  {
    "stt": 71,
    "code": "",
    "name": "Mr. Mai Đức Trung",
    "dept": "HĐQT",
    "subdept": "",
    "pos": "Khách",
    "gender": "Nam",
    "company": "Phú Anh",
    "isGala": false
  },
  {
    "stt": 72,
    "code": "",
    "name": "Mr. Vũ Mạnh Sơn",
    "dept": "HĐQT",
    "subdept": "",
    "pos": "Khách",
    "gender": "Nam",
    "company": "Phú Anh",
    "isGala": false
  },
  {
    "stt": 73,
    "code": "",
    "name": "Đinh Thị Thu Hà",
    "dept": "NV cũ",
    "subdept": "",
    "pos": "Khách",
    "gender": "Nữ",
    "company": "Phú Anh",
    "isGala": true
  },
  {
    "stt": 74,
    "code": "116",
    "name": "Vũ Thị Việt Phương",
    "dept": "Kinh doanh",
    "subdept": "Phát triển thị trường",
    "pos": "Chuyên viên Kinh doanh",
    "gender": "Nữ",
    "company": "Tà Lùng Quang Minh",
    "isGala": true
  },
  {
    "stt": 75,
    "code": "020",
    "name": "Nông Ngọc Chương",
    "dept": "Vận hành",
    "subdept": "An ninh",
    "pos": "Nhân viên An ninh",
    "gender": "Nam",
    "company": "Phú Anh",
    "isGala": false
  },
  {
    "stt": 76,
    "code": "023",
    "name": "Hoàng Quốc Tế",
    "dept": "Vận hành",
    "subdept": "An ninh",
    "pos": "Nhân viên An ninh",
    "gender": "Nam",
    "company": "Phú Anh",
    "isGala": false
  },
  {
    "stt": 77,
    "code": "026",
    "name": "Nguyễn Đức Anh",
    "dept": "Vận hành",
    "subdept": "An ninh",
    "pos": "Nhân viên An ninh",
    "gender": "Nam",
    "company": "Phú Anh",
    "isGala": false
  },
  {
    "stt": 78,
    "code": "044",
    "name": "Chu Văn Vương",
    "dept": "Vận hành",
    "subdept": "An ninh",
    "pos": "Nhân viên An ninh",
    "gender": "Nam",
    "company": "Phú Anh",
    "isGala": false
  },
  {
    "stt": 79,
    "code": "063",
    "name": "Đàm Văn Thế",
    "dept": "Vận hành",
    "subdept": "An ninh",
    "pos": "Nhân viên An ninh",
    "gender": "Nam",
    "company": "Sơn Cảng",
    "isGala": false
  },
  {
    "stt": 80,
    "code": "064",
    "name": "Triệu Đại Dương",
    "dept": "Vận hành",
    "subdept": "An ninh",
    "pos": "Nhân viên An ninh",
    "gender": "Nam",
    "company": "Sơn Cảng",
    "isGala": false
  },
  {
    "stt": 81,
    "code": "091",
    "name": "Phùng Văn Trần",
    "dept": "Vận hành",
    "subdept": "An ninh",
    "pos": "Nhân viên An ninh",
    "gender": "Nam",
    "company": "Sơn Cảng",
    "isGala": false
  },
  {
    "stt": 82,
    "code": "107",
    "name": "Đinh Văn Thọ",
    "dept": "Vận hành",
    "subdept": "An ninh",
    "pos": "Nhân viên An ninh",
    "gender": "Nam",
    "company": "Sơn Cảng",
    "isGala": false
  },
  {
    "stt": 83,
    "code": "118",
    "name": "Nông Quang Khải",
    "dept": "Vận hành",
    "subdept": "An ninh",
    "pos": "Nhân viên An ninh",
    "gender": "Nam",
    "company": "Sơn Cảng",
    "isGala": false
  },
  {
    "stt": 84,
    "code": "132",
    "name": "Triệu Phi Hùng",
    "dept": "Vận hành",
    "subdept": "An ninh",
    "pos": "Nhân viên An ninh",
    "gender": "Nam",
    "company": "Sơn Cảng",
    "isGala": false
  },
  {
    "stt": 85,
    "code": "085",
    "name": "Nguyễn Bá Hướng",
    "dept": "Vận hành",
    "subdept": "Điều phối",
    "pos": "Công nhân bốc xếp",
    "gender": "Nam",
    "company": "Sơn Cảng",
    "isGala": false
  },
  {
    "stt": 86,
    "code": "088",
    "name": "Ma Văn Quyết",
    "dept": "Vận hành",
    "subdept": "Điều phối",
    "pos": "Công nhân bốc xếp",
    "gender": "Nam",
    "company": "Sơn Cảng",
    "isGala": false
  },
  {
    "stt": 87,
    "code": "125",
    "name": "Nông Văn Dương",
    "dept": "Vận hành",
    "subdept": "Điều phối",
    "pos": "Công nhân bốc xếp",
    "gender": "Nam",
    "company": "Sơn Cảng",
    "isGala": false
  },
  {
    "stt": 88,
    "code": "140",
    "name": "Lương Quốc Bảo",
    "dept": "Vận hành",
    "subdept": "Điều phối",
    "pos": "Công nhân bốc xếp",
    "gender": "Nam",
    "company": "Sơn Cảng",
    "isGala": false
  },
  {
    "stt": 89,
    "code": "019",
    "name": "Hà Đức Thông",
    "dept": "Vận hành",
    "subdept": "Điều phối",
    "pos": "Nhân viên Điều phối",
    "gender": "Nam",
    "company": "Phú Anh",
    "isGala": false
  },
  {
    "stt": 90,
    "code": "021",
    "name": "Linh Minh Trọng",
    "dept": "Vận hành",
    "subdept": "Điều phối",
    "pos": "Nhân viên Điều phối",
    "gender": "Nam",
    "company": "Sơn Cảng",
    "isGala": false
  },
  {
    "stt": 91,
    "code": "024",
    "name": "Trần Văn Hải",
    "dept": "Vận hành",
    "subdept": "Điều phối",
    "pos": "Nhân viên Điều phối",
    "gender": "Nam",
    "company": "Phú Anh",
    "isGala": false
  },
  {
    "stt": 92,
    "code": "025",
    "name": "Bùi Hải Long",
    "dept": "Vận hành",
    "subdept": "Điều phối",
    "pos": "Nhân viên Điều phối",
    "gender": "Nam",
    "company": "Phú Anh",
    "isGala": false
  },
  {
    "stt": 93,
    "code": "110",
    "name": "Phan Ngọc Anh",
    "dept": "Vận hành",
    "subdept": "Điều phối",
    "pos": "Nhân viên Điều phối",
    "gender": "Nam",
    "company": "Song Toàn",
    "isGala": false
  },
  {
    "stt": 94,
    "code": "018",
    "name": "Lý Văn Khanh",
    "dept": "Vận hành",
    "subdept": "Điều phối",
    "pos": "Nhân viên nghiệp vụ cổng cảng và kho bãi",
    "gender": "Nam",
    "company": "Phú Anh",
    "isGala": false
  },
  {
    "stt": 95,
    "code": "014",
    "name": "Nguyễn Đức Quyết",
    "dept": "Vận hành",
    "subdept": "Hành chính",
    "pos": "Nhân viên Thẩm định - Mua sắm",
    "gender": "Nam",
    "company": "Phú Anh",
    "isGala": false
  },
  {
    "stt": 96,
    "code": "065",
    "name": "Lục Thị Tuyết Nhi",
    "dept": "Vận hành",
    "subdept": "Hành chính",
    "pos": "Thư ký phòng vận hành",
    "gender": "Nữ",
    "company": "Sơn Cảng",
    "isGala": false
  },
  {
    "stt": 97,
    "code": "036",
    "name": "Hoàng Văn Sinh",
    "dept": "Vận hành",
    "subdept": "Kỹ thuật",
    "pos": "Nhân viên Kỹ thuật",
    "gender": "Nam",
    "company": "Phú Anh",
    "isGala": true
  },
  {
    "stt": 98,
    "code": "045",
    "name": "Hoàng Cao Hiệp",
    "dept": "Vận hành",
    "subdept": "Kỹ thuật",
    "pos": "Nhân viên Kỹ thuật",
    "gender": "Nam",
    "company": "Phú Anh",
    "isGala": false
  },
  {
    "stt": 99,
    "code": "084",
    "name": "Nông Trung Lực",
    "dept": "Vận hành",
    "subdept": "Vận hành thiết bị",
    "pos": "Nhân viên vận hành thiết bị",
    "gender": "Nam",
    "company": "Sơn Cảng",
    "isGala": false
  },
  {
    "stt": 100,
    "code": "099",
    "name": "Nông Văn Hùng",
    "dept": "Vận hành",
    "subdept": "Vận hành thiết bị",
    "pos": "Nhân viên vận hành thiết bị",
    "gender": "Nam",
    "company": "Sơn Cảng",
    "isGala": false
  },
  {
    "stt": 101,
    "code": "105",
    "name": "Linh Văn Hiệu",
    "dept": "Vận hành",
    "subdept": "Vận hành thiết bị",
    "pos": "Nhân viên vận hành thiết bị",
    "gender": "Nam",
    "company": "Sơn Cảng",
    "isGala": false
  },
  {
    "stt": 102,
    "code": "136",
    "name": "Bế Ích Thiệp",
    "dept": "Vận hành",
    "subdept": "Vận hành thiết bị",
    "pos": "Nhân viên vận hành thiết bị",
    "gender": "Nam",
    "company": "Sơn Cảng",
    "isGala": false
  },
  {
    "stt": 103,
    "code": "137",
    "name": "Chu Văn Kinh",
    "dept": "Vận hành",
    "subdept": "Vận hành thiết bị",
    "pos": "Nhân viên vận hành thiết bị",
    "gender": "Nam",
    "company": "Sơn Cảng",
    "isGala": false
  },
  {
    "stt": 111,
    "code": "",
    "name": "Tổng cộng",
    "dept": "",
    "subdept": "",
    "pos": "",
    "gender": "",
    "company": "Tà Lùng Quang Minh",
    "isGala": false
  }
];
